import cv2, numpy as np, collections, os, sys

ROOT = r'C:\Users\Jeron\Documents\Programming\Pokemon\Arduino-Source'
CANDS = [
    os.path.join(ROOT, r'SerialPrograms\Resources\PokemonFRLG\Maps\Kanto-Combined.png'),
    os.path.join(ROOT, r'Packages\Resources\PokemonFRLG\Maps\Kanto-Combined.png'),
    os.path.join(ROOT, r'build-msvc-qt683\RelWithDebInfo\Resources\PokemonFRLG\Maps\Kanto-Combined.png'),
]
MAP = next((p for p in CANDS if os.path.exists(p)), None)
print("using map:", MAP)
img = cv2.imread(MAP, cv2.IMREAD_COLOR)
T=16
ROWS, COLS = img.shape[0]//T, img.shape[1]//T
grid = img.reshape(ROWS,T,COLS,T,3).transpose(0,2,1,3,4)
flat = np.ascontiguousarray(grid).reshape(ROWS,COLS,T*T*3)

MID = flat[205][42].tobytes()
pos = [(x,y) for y in range(ROWS) for x in range(COLS) if flat[y][x].tobytes()==MID]
left = collections.Counter(); right = collections.Counter()
for (x,y) in pos:
    if x>0:
        k=flat[y][x-1].tobytes()
        if k!=MID: left[k]+=1
    if x<COLS-1:
        k=flat[y][x+1].tobytes()
        if k!=MID: right[k]+=1
LCAP = left.most_common(1)[0][0]
RCAP = right.most_common(1)[0][0]
FAMILY = {MID, LCAP, RCAP}

ledges=[]
for y in range(ROWS):
    r=flat[y]
    for x in range(COLS):
        if r[x].tobytes() in FAMILY:
            ledges.append((x,y))
print("ledge tiles found: %d" % len(ledges))

# sanity: how many are usable hops (walkable-looking ground two rows down is
# not something we can judge here, but y bounds are)
usable = [(x,y) for (x,y) in ledges if 0 < y < ROWS-1]
print("with a tile above and below: %d" % len(usable))

keys = sorted(y*COLS + x for (x,y) in usable)
out = os.path.join(ROOT, r'SerialPrograms\Source\PokemonFRLG\Inference\Map\PokemonFRLG_KantoLedges_Generated.h')
with open(out,'w',newline='\n') as f:
    f.write("/*  Kanto South-Facing Ledges (generated)\n")
    f.write(" *\n")
    f.write(" *  From: https://github.com/PokemonAutomation/\n")
    f.write(" *\n")
    f.write(" *  GENERATED by Scripts/PokemonFRLG/generate_kanto_ledges.py -- do not hand edit.\n")
    f.write(" *\n")
    f.write(" *  Gen 3 ledges are one-way: you hop south over them and cannot walk back up.\n")
    f.write(" *  Found by exact tile matching against the combined Kanto map, which is built\n")
    f.write(" *  from a %d-tile alphabet, so a ledge sprite matches byte-for-byte everywhere\n" % 1791)
    f.write(" *  it appears. The family is three tiles: the repeating middle plus a rounded\n")
    f.write(" *  cap at each end of a run.\n")
    f.write(" *\n")
    f.write(" *  Entries are (y * %d + x), sorted, for binary search.\n" % COLS)
    f.write(" */\n\n")
    f.write("#ifndef PokemonAutomation_PokemonFRLG_KantoLedges_Generated_H\n")
    f.write("#define PokemonAutomation_PokemonFRLG_KantoLedges_Generated_H\n\n")
    f.write("#include <cstdint>\n\n")
    f.write("namespace PokemonAutomation{\nnamespace NintendoSwitch{\nnamespace PokemonFRLG{\n\n")
    f.write("constexpr int KANTO_LEDGE_COLS = %d;\n\n" % COLS)
    f.write("constexpr uint32_t KANTO_LEDGE_SOUTH[] = {\n")
    for i in range(0, len(keys), 12):
        f.write("    " + ", ".join(str(k) for k in keys[i:i+12]) + ",\n")
    f.write("};\n")
    f.write("constexpr int KANTO_LEDGE_SOUTH_COUNT = %d;\n\n" % len(keys))
    f.write("}\n}\n}\n#endif\n")
print("wrote", out)

# report a few known spots for sanity
for probe in [(42,205),(43,205),(41,205),(45,205),(44,205)]:
    print("   (%d,%d) is ledge: %s" % (probe[0],probe[1], (probe[1]*COLS+probe[0]) in set(keys)))
