"""Generate PokemonFRLG_KantoMaskCorrections_Generated.h

The Kanto walkable mask is auto-classified from the combined map image, and it
turns out to be *perfectly consistent per tile identity*: all 1791 distinct
16x16 tiles are classified unanimously across all 163,200 map cells. Nothing is
misclassified in one place and right in another.

That means every mask error is a per-TILE error, and correcting one tile fixes
every instance of it across Kanto at once -- which is far better than the
per-location rectangles we had been adding one dead run at a time.

Each entry below names a tile by a reference cell where we have PROVEN the
classification wrong by walking into it, plus what the tile actually is. The
script finds every copy of that tile and emits its cells as force-blocked.

Re-run after any change to Kanto-Combined.png or the generated mask.
"""

import cv2, numpy as np, re, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
MAP  = os.path.join(ROOT, 'Packages', 'Resources', 'PokemonFRLG', 'Maps', 'Kanto-Combined.png')
MH   = os.path.join(ROOT, 'SerialPrograms', 'Source', 'PokemonFRLG', 'Inference', 'Map',
                    'PokemonFRLG_KantoMapMasks_Generated.h')
OUT  = os.path.join(ROOT, 'SerialPrograms', 'Source', 'PokemonFRLG', 'Inference', 'Map',
                    'PokemonFRLG_KantoMaskCorrections_Generated.h')

#  (reference cell, what the tile actually is, where we proved it)
FORCE_BLOCKED = [
    ((40, 200), "tree canopy, light green",
     "Route 22 tree column: walked into it 2026-08-19, also Route 1 rows 215/216"),
    ((41, 200), "tree canopy, light green",
     "Route 22 tree column, second column"),
    ((50, 203), "mountain rock face",
     "Route 22 mountain interior: A* routed through it 2026-08-19 and the player "
     "pressed south into the rock eight times"),
]

img = cv2.imread(MAP, cv2.IMREAD_COLOR)
if img is None:
    print("cannot read map:", MAP); sys.exit(1)
T = 16
ROWS, COLS = img.shape[0]//T, img.shape[1]//T
grid = img.reshape(ROWS, T, COLS, T, 3).transpose(0, 2, 1, 3, 4)
flat = np.ascontiguousarray(grid).reshape(ROWS, COLS, T*T*3)

txt = open(MH, 'r', encoding='utf-8', errors='replace').read()
m = re.search(r'KANTO_MASK\[(\d+)\]\[(\d+)\]\s*=\s*\{(.*?)\n\};', txt, re.S)
rows = []
for line in m.group(3).splitlines():
    line = line.strip()
    if line.startswith('{'):
        n = re.findall(r'\d+', line)
        if len(n) == COLS:
            rows.append([int(v) for v in n])

cells = set()
report = []
for (rx, ry), what, why in FORCE_BLOCKED:
    key = flat[ry][rx].tobytes()
    hits = [(x, y) for y in range(ROWS) for x in range(COLS) if flat[y][x].tobytes() == key]
    already = sum(1 for (x, y) in hits if rows[y][x] != 0)
    for h in hits:
        cells.add(h)
    report.append((rx, ry, what, len(hits), already))
    print("(%3d,%3d) %-26s %5d copies, %d already blocked" % (rx, ry, what, len(hits), already))

keys = sorted(y*COLS + x for (x, y) in cells)
print("total cells force-blocked: %d" % len(keys))

with open(OUT, 'w', newline='\n') as f:
    f.write("/*  Kanto Walkable-Mask Corrections (generated)\n *\n")
    f.write(" *  From: https://github.com/PokemonAutomation/\n *\n")
    f.write(" *  GENERATED by Scripts/PokemonFRLG/generate_kanto_mask_corrections.py\n")
    f.write(" *  -- do not hand edit.\n *\n")
    f.write(" *  The generated mask is perfectly consistent per tile identity: all 1791\n")
    f.write(" *  distinct tiles are classified unanimously across all %d cells. So every\n" % (ROWS*COLS))
    f.write(" *  mask error is a per-TILE error, and correcting one tile fixes every copy\n")
    f.write(" *  of it across Kanto at once.\n *\n")
    f.write(" *  Tiles corrected here (each proven wrong by walking into it):\n")
    for rx, ry, what, n, already in report:
        f.write(" *      (%3d,%3d)  %-26s %5d copies\n" % (rx, ry, what, n))
    f.write(" *\n *  Entries are (y * %d + x), sorted, for binary search.\n */\n\n" % COLS)
    f.write("#ifndef PokemonAutomation_PokemonFRLG_KantoMaskCorrections_Generated_H\n")
    f.write("#define PokemonAutomation_PokemonFRLG_KantoMaskCorrections_Generated_H\n\n")
    f.write("#include <cstdint>\n\n")
    f.write("namespace PokemonAutomation{\nnamespace NintendoSwitch{\nnamespace PokemonFRLG{\n\n")
    f.write("constexpr int KANTO_CORRECTION_COLS = %d;\n\n" % COLS)
    f.write("constexpr uint32_t KANTO_FORCE_BLOCKED[] = {\n")
    for i in range(0, len(keys), 12):
        f.write("    " + ", ".join(str(k) for k in keys[i:i+12]) + ",\n")
    f.write("};\n")
    f.write("constexpr int KANTO_FORCE_BLOCKED_COUNT = %d;\n\n" % len(keys))
    f.write("}\n}\n}\n#endif\n")
print("wrote", OUT)
