/*  Kanto Extended Goals (generated)
 *
 *  GENERATED by Scripts/PokemonFRLG/generate_kanto_full_map.py -- do not hand edit.
 *  Every building/cave/gym/pokecenter door (warp_events) and every Fly
 *  destination (heal_locations.json), in global combined-map tile coords.
 *  Door goal count: 201. Fly goal count: 13.
 */

#ifndef PokemonAutomation_PokemonFRLG_KantoGoals_Extended_H
#define PokemonAutomation_PokemonFRLG_KantoGoals_Extended_H

//  NOTE: this worktree doesn't have Scripts/PokemonFRLG/generate_kanto_full_map.py
//  (added on a sibling branch), so the include path below was hand-fixed to
//  resolve from this file's actual directory (Inference/Map/) rather than
//  regenerated. If the generator script lands here later, verify it emits
//  this same relative path.
#include "PokemonFRLG/Programs/PokemonFRLG_KantoMapNavigator.h"

namespace PokemonAutomation{
namespace NintendoSwitch{
namespace PokemonFRLG{
namespace KantoGoals{
namespace Extended{

//  ---- Every building / cave / gym / pokecenter door (from warp_events) ----
constexpr KantoGoal PalletTownPlayersHouse1fDoor             {  66,  267, 1};  // -> MAP_PALLET_TOWN_PLAYERS_HOUSE_1F
constexpr KantoGoal PalletTownRivalsHouseDoor                {  75,  267, 1};  // -> MAP_PALLET_TOWN_RIVALS_HOUSE
constexpr KantoGoal PalletTownProfessorOaksLabDoor           {  76,  273, 1};  // -> MAP_PALLET_TOWN_PROFESSOR_OAKS_LAB
constexpr KantoGoal ViridianCityPokemonCenter1fDoor          {  74,  206, 1};  // -> MAP_VIRIDIAN_CITY_POKEMON_CENTER_1F
constexpr KantoGoal ViridianCityHouseDoor                    {  73,  191, 1};  // -> MAP_VIRIDIAN_CITY_HOUSE
constexpr KantoGoal ViridianCityGymDoor                      {  84,  190, 1};  // -> MAP_VIRIDIAN_CITY_GYM
constexpr KantoGoal ViridianCitySchoolDoor                   {  73,  198, 1};  // -> MAP_VIRIDIAN_CITY_SCHOOL
constexpr KantoGoal ViridianCityMartDoor                     {  84,  199, 1};  // -> MAP_VIRIDIAN_CITY_MART
constexpr KantoGoal Route2ViridianForestNorthEntranceDoor1   {  65,  113, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE
constexpr KantoGoal Route2ViridianForestNorthEntranceDoor2   {  66,  113, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE
constexpr KantoGoal Route2ViridianForestSouthEntranceDoor1   {  65,  151, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE
constexpr KantoGoal DiglettsCaveNorthEntranceDoor1           {  77,  111, 1};  // -> MAP_DIGLETTS_CAVE_NORTH_ENTRANCE
constexpr KantoGoal Route2HouseDoor                          {  77,  122, 1};  // -> MAP_ROUTE2_HOUSE
constexpr KantoGoal Route2EastBuildingDoor1                  {  78,  146, 1};  // -> MAP_ROUTE2_EAST_BUILDING
constexpr KantoGoal Route2EastBuildingDoor2                  {  78,  141, 1};  // -> MAP_ROUTE2_EAST_BUILDING
constexpr KantoGoal Route2EastBuildingDoor3                  {  79,  141, 1};  // -> MAP_ROUTE2_EAST_BUILDING
constexpr KantoGoal Route2EastBuildingDoor4                  {  79,  146, 1};  // -> MAP_ROUTE2_EAST_BUILDING
constexpr KantoGoal Route2ViridianForestSouthEntranceDoor2   {  66,  151, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE
constexpr KantoGoal Route22NorthEntranceDoor1                {   8,  195, 1};  // -> MAP_ROUTE22_NORTH_ENTRANCE
constexpr KantoGoal Route22NorthEntranceDoor2                {   9,  195, 1};  // -> MAP_ROUTE22_NORTH_ENTRANCE
constexpr KantoGoal PokemonMansion1fDoor                     {  68,  383, 1};  // -> MAP_POKEMON_MANSION_1F
constexpr KantoGoal CinnabarIslandGymDoor                    {  80,  384, 1};  // -> MAP_CINNABAR_ISLAND_GYM
constexpr KantoGoal CinnabarIslandPokemonLabEntranceDoor     {  68,  389, 1};  // -> MAP_CINNABAR_ISLAND_POKEMON_LAB_ENTRANCE
constexpr KantoGoal CinnabarIslandPokemonCenter1fDoor        {  74,  391, 1};  // -> MAP_CINNABAR_ISLAND_POKEMON_CENTER_1F
constexpr KantoGoal CinnabarIslandMartDoor                   {  79,  391, 1};  // -> MAP_CINNABAR_ISLAND_MART
constexpr KantoGoal PewterCityMuseum1fDoor1                  {  65,   66, 1};  // -> MAP_PEWTER_CITY_MUSEUM_1F
constexpr KantoGoal PewterCityMuseum1fDoor2                  {  73,   64, 1};  // -> MAP_PEWTER_CITY_MUSEUM_1F
constexpr KantoGoal PewterCityGymDoor                        {  63,   76, 1};  // -> MAP_PEWTER_CITY_GYM
constexpr KantoGoal PewterCityMartDoor                       {  76,   78, 1};  // -> MAP_PEWTER_CITY_MART
constexpr KantoGoal PewterCityHouse1Door                     {  81,   71, 1};  // -> MAP_PEWTER_CITY_HOUSE1
constexpr KantoGoal PewterCityPokemonCenter1fDoor            {  65,   85, 1};  // -> MAP_PEWTER_CITY_POKEMON_CENTER_1F
constexpr KantoGoal PewterCityHouse2Door                     {  57,   90, 1};  // -> MAP_PEWTER_CITY_HOUSE2
constexpr KantoGoal VictoryRoad1fDoor                        {   5,   58, 1};  // -> MAP_VICTORY_ROAD_1F
constexpr KantoGoal VictoryRoad2fDoor                        {  18,   58, 1};  // -> MAP_VICTORY_ROAD_2F
constexpr KantoGoal Route22NorthEntranceDoor3                {   8,  183, 1};  // -> MAP_ROUTE22_NORTH_ENTRANCE
constexpr KantoGoal Route22NorthEntranceDoor4                {   9,  184, 1};  // -> MAP_ROUTE22_NORTH_ENTRANCE
constexpr KantoGoal SeafoamIslands1fDoor1                    { 144,  388, 1};  // -> MAP_SEAFOAM_ISLANDS_1F
constexpr KantoGoal SeafoamIslands1fDoor2                    { 156,  394, 1};  // -> MAP_SEAFOAM_ISLANDS_1F
constexpr KantoGoal IndigoPlateauPokemonCenter1fDoor         {  11,   16, 1};  // -> MAP_INDIGO_PLATEAU_POKEMON_CENTER_1F
constexpr KantoGoal MtMoon1fDoor1                            { 175,   55, 1};  // -> MAP_MT_MOON_1F
constexpr KantoGoal MtMoonB1fDoor1                           { 188,   55, 1};  // -> MAP_MT_MOON_B1F
constexpr KantoGoal Route4PokemonCenter1fDoor                { 168,   55, 1};  // -> MAP_ROUTE4_POKEMON_CENTER_1F
constexpr KantoGoal FuchsiaCitySafariZoneEntranceDoor        { 216,  305, 1};  // -> MAP_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE
constexpr KantoGoal FuchsiaCityWardensHouseDoor              { 225,  331, 1};  // -> MAP_FUCHSIA_CITY_WARDENS_HOUSE
constexpr KantoGoal FuchsiaCityMartDoor                      { 203,  315, 1};  // -> MAP_FUCHSIA_CITY_MART
constexpr KantoGoal FuchsiaCitySafariZoneOfficeDoor          { 220,  316, 1};  // -> MAP_FUCHSIA_CITY_SAFARI_ZONE_OFFICE
constexpr KantoGoal FuchsiaCityGymDoor                       { 201,  332, 1};  // -> MAP_FUCHSIA_CITY_GYM
constexpr KantoGoal FuchsiaCityHouse1Door                    { 206,  331, 1};  // -> MAP_FUCHSIA_CITY_HOUSE1
constexpr KantoGoal FuchsiaCityPokemonCenter1fDoor           { 217,  331, 1};  // -> MAP_FUCHSIA_CITY_POKEMON_CENTER_1F
constexpr KantoGoal FuchsiaCityHouse2Door1                   { 230,  331, 1};  // -> MAP_FUCHSIA_CITY_HOUSE2
constexpr KantoGoal FuchsiaCityHouse2Door2                   { 231,  328, 1};  // -> MAP_FUCHSIA_CITY_HOUSE2
constexpr KantoGoal FuchsiaCityHouse2Door3                   { 231,  329, 1};  // -> MAP_FUCHSIA_CITY_HOUSE2
constexpr KantoGoal FuchsiaCityHouse3Door                    { 211,  331, 1};  // -> MAP_FUCHSIA_CITY_HOUSE3
constexpr KantoGoal CeruleanCityHouse1Door1                  { 274,   51, 1};  // -> MAP_CERULEAN_CITY_HOUSE1
constexpr KantoGoal CeruleanCityHouse2Door1                  { 294,   51, 1};  // -> MAP_CERULEAN_CITY_HOUSE2
constexpr KantoGoal CeruleanCityHouse3Door                   { 279,   57, 1};  // -> MAP_CERULEAN_CITY_HOUSE3
constexpr KantoGoal CeruleanCityPokemonCenter1fDoor          { 286,   59, 1};  // -> MAP_CERULEAN_CITY_POKEMON_CENTER_1F
constexpr KantoGoal CeruleanCityGymDoor                      { 295,   61, 1};  // -> MAP_CERULEAN_CITY_GYM
constexpr KantoGoal CeruleanCityBikeShopDoor1                { 277,   68, 1};  // -> MAP_CERULEAN_CITY_BIKE_SHOP
constexpr KantoGoal CeruleanCityMartDoor                     { 293,   68, 1};  // -> MAP_CERULEAN_CITY_MART
constexpr KantoGoal CeruleanCave1fDoor1                      { 265,   52, 1};  // -> MAP_CERULEAN_CAVE_1F
constexpr KantoGoal CeruleanCityHouse1Door2                  { 274,   48, 1};  // -> MAP_CERULEAN_CITY_HOUSE1
constexpr KantoGoal CeruleanCityHouse2Door2                  { 295,   48, 1};  // -> MAP_CERULEAN_CITY_HOUSE2
constexpr KantoGoal CeruleanCityHouse2Door3                  { 295,   49, 1};  // -> MAP_CERULEAN_CITY_HOUSE2
constexpr KantoGoal CeruleanCityBikeShopDoor2                { 278,   68, 1};  // -> MAP_CERULEAN_CITY_BIKE_SHOP
constexpr KantoGoal CeruleanCityHouse4Door                   { 287,   68, 1};  // -> MAP_CERULEAN_CITY_HOUSE4
constexpr KantoGoal CeruleanCityHouse5Door                   { 281,   51, 1};  // -> MAP_CERULEAN_CITY_HOUSE5
constexpr KantoGoal Route18EastEntrance1fDoor1               { 173,  319, 1};  // -> MAP_ROUTE18_EAST_ENTRANCE_1F
constexpr KantoGoal Route18EastEntrance1fDoor2               { 180,  319, 1};  // -> MAP_ROUTE18_EAST_ENTRANCE_1F
constexpr KantoGoal Route15WestEntrance1fDoor1               { 249,  321, 1};  // -> MAP_ROUTE15_WEST_ENTRANCE_1F
constexpr KantoGoal Route15WestEntrance1fDoor2               { 256,  321, 1};  // -> MAP_ROUTE15_WEST_ENTRANCE_1F
constexpr KantoGoal UndergroundPathNorthEntranceDoor1        { 295,  111, 1};  // -> MAP_UNDERGROUND_PATH_NORTH_ENTRANCE
constexpr KantoGoal Route5PokemonDayCareDoor                 { 287,  105, 1};  // -> MAP_ROUTE5_POKEMON_DAY_CARE
constexpr KantoGoal Route5SouthEntranceDoor1                 { 288,  112, 1};  // -> MAP_ROUTE5_SOUTH_ENTRANCE
constexpr KantoGoal Route5SouthEntranceDoor2                 { 289,  112, 1};  // -> MAP_ROUTE5_SOUTH_ENTRANCE
constexpr KantoGoal Route25SeaCottageDoor                    { 351,    4, 1};  // -> MAP_ROUTE25_SEA_COTTAGE
constexpr KantoGoal RockTunnel1fDoor1                        { 392,   69, 1};  // -> MAP_ROCK_TUNNEL_1F
constexpr KantoGoal RockTunnel1fDoor2                        { 392,  107, 1};  // -> MAP_ROCK_TUNNEL_1F
constexpr KantoGoal PowerPlantDoor1                          { 391,   90, 1};  // -> MAP_POWER_PLANT
constexpr KantoGoal Route10PokemonCenter1fDoor               { 397,   70, 1};  // -> MAP_ROUTE10_POKEMON_CENTER_1F
constexpr KantoGoal PowerPlantDoor2                          { 386,   87, 1};  // -> MAP_POWER_PLANT
constexpr KantoGoal Route16HouseDoor                         { 142,  135, 1};  // -> MAP_ROUTE16_HOUSE
constexpr KantoGoal Route16NorthEntrance1fDoor1              { 152,  136, 1};  // -> MAP_ROUTE16_NORTH_ENTRANCE_1F
constexpr KantoGoal Route16NorthEntrance1fDoor2              { 159,  136, 1};  // -> MAP_ROUTE16_NORTH_ENTRANCE_1F
constexpr KantoGoal Route16NorthEntrance1fDoor3              { 152,  143, 1};  // -> MAP_ROUTE16_NORTH_ENTRANCE_1F
constexpr KantoGoal Route16NorthEntrance1fDoor4              { 159,  143, 1};  // -> MAP_ROUTE16_NORTH_ENTRANCE_1F
constexpr KantoGoal UndergroundPathSouthEntranceDoor1        { 295,  173, 1};  // -> MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE
constexpr KantoGoal Route6NorthEntranceDoor1                 { 288,  165, 1};  // -> MAP_ROUTE6_NORTH_ENTRANCE
constexpr KantoGoal Route6NorthEntranceDoor2                 { 289,  165, 1};  // -> MAP_ROUTE6_NORTH_ENTRANCE
constexpr KantoGoal UndergroundPathWestEntranceDoor1         { 247,  144, 1};  // -> MAP_UNDERGROUND_PATH_WEST_ENTRANCE
constexpr KantoGoal Route7EastEntranceDoor1                  { 255,  140, 1};  // -> MAP_ROUTE7_EAST_ENTRANCE
constexpr KantoGoal UndergroundPathEastEntranceDoor1         { 325,  134, 1};  // -> MAP_UNDERGROUND_PATH_EAST_ENTRANCE
constexpr KantoGoal Route8WestEntranceDoor1                  { 319,  140, 1};  // -> MAP_ROUTE8_WEST_ENTRANCE
constexpr KantoGoal PokemonTower1fDoor                       { 402,  136, 1};  // -> MAP_POKEMON_TOWER_1F
constexpr KantoGoal LavenderTownPokemonCenter1fDoor          { 390,  135, 1};  // -> MAP_LAVENDER_TOWN_POKEMON_CENTER_1F
constexpr KantoGoal LavenderTownVolunteerPokemonHouseDoor    { 394,  141, 1};  // -> MAP_LAVENDER_TOWN_VOLUNTEER_POKEMON_HOUSE
constexpr KantoGoal LavenderTownHouse1Door                   { 389,  146, 1};  // -> MAP_LAVENDER_TOWN_HOUSE1
constexpr KantoGoal LavenderTownHouse2Door                   { 394,  146, 1};  // -> MAP_LAVENDER_TOWN_HOUSE2
constexpr KantoGoal LavenderTownMartDoor                     { 404,  145, 1};  // -> MAP_LAVENDER_TOWN_MART
constexpr KantoGoal CeladonCityGameCornerDoor                { 214,  141, 1};  // -> MAP_CELADON_CITY_GAME_CORNER
constexpr KantoGoal CeladonCityDepartmentStore1fDoor1        { 191,  134, 1};  // -> MAP_CELADON_CITY_DEPARTMENT_STORE_1F
constexpr KantoGoal CeladonCityDepartmentStore1fDoor2        { 195,  134, 1};  // -> MAP_CELADON_CITY_DEPARTMENT_STORE_1F
constexpr KantoGoal CeladonCityCondominiums1fDoor1           { 210,  131, 1};  // -> MAP_CELADON_CITY_CONDOMINIUMS_1F
constexpr KantoGoal CeladonCityPokemonCenter1fDoor           { 228,  131, 1};  // -> MAP_CELADON_CITY_POKEMON_CENTER_1F
constexpr KantoGoal CeladonCityGameCornerPrizeRoomDoor       { 219,  140, 1};  // -> MAP_CELADON_CITY_GAME_CORNER_PRIZE_ROOM
constexpr KantoGoal CeladonCityGymDoor                       { 191,  150, 1};  // -> MAP_CELADON_CITY_GYM
constexpr KantoGoal CeladonCityRestaurantDoor                { 217,  149, 1};  // -> MAP_CELADON_CITY_RESTAURANT
constexpr KantoGoal CeladonCityHouse1Door                    { 221,  149, 1};  // -> MAP_CELADON_CITY_HOUSE1
constexpr KantoGoal CeladonCityHotelDoor                     { 229,  149, 1};  // -> MAP_CELADON_CITY_HOTEL
constexpr KantoGoal CeladonCityCondominiums1fDoor2           { 209,  125, 1};  // -> MAP_CELADON_CITY_CONDOMINIUMS_1F
constexpr KantoGoal CeladonCityCondominiums1fDoor3           { 210,  124, 1};  // -> MAP_CELADON_CITY_CONDOMINIUMS_1F
constexpr KantoGoal CeladonCityCondominiums1fDoor4           { 211,  125, 1};  // -> MAP_CELADON_CITY_CONDOMINIUMS_1F
constexpr KantoGoal Route12FishingHouseDoor                  { 396,  236, 1};  // -> MAP_ROUTE12_FISHING_HOUSE
constexpr KantoGoal Route12NorthEntrance1fDoor1              { 398,  165, 1};  // -> MAP_ROUTE12_NORTH_ENTRANCE_1F
constexpr KantoGoal Route12NorthEntrance1fDoor2              { 399,  165, 1};  // -> MAP_ROUTE12_NORTH_ENTRANCE_1F
constexpr KantoGoal Route12NorthEntrance1fDoor3              { 398,  171, 1};  // -> MAP_ROUTE12_NORTH_ENTRANCE_1F
constexpr KantoGoal SsanneExteriorDoor1                      { 286,  234, 1};  // -> MAP_SSANNE_EXTERIOR
constexpr KantoGoal SsanneExteriorDoor2                      { 287,  234, 1};  // -> MAP_SSANNE_EXTERIOR
constexpr KantoGoal SsanneExteriorDoor3                      { 288,  234, 1};  // -> MAP_SSANNE_EXTERIOR
constexpr KantoGoal VermilionCityHouse1Door                  { 273,  206, 1};  // -> MAP_VERMILION_CITY_HOUSE1
constexpr KantoGoal VermilionCityPokemonCenter1fDoor         { 279,  206, 1};  // -> MAP_VERMILION_CITY_POKEMON_CENTER_1F
constexpr KantoGoal VermilionCityPokemonFanClubDoor          { 276,  217, 1};  // -> MAP_VERMILION_CITY_POKEMON_FAN_CLUB
constexpr KantoGoal VermilionCityHouse2Door                  { 283,  217, 1};  // -> MAP_VERMILION_CITY_HOUSE2
constexpr KantoGoal VermilionCityMartDoor                    { 293,  217, 1};  // -> MAP_VERMILION_CITY_MART
constexpr KantoGoal VermilionCityHouse3Door                  { 292,  224, 1};  // -> MAP_VERMILION_CITY_HOUSE3
constexpr KantoGoal VermilionCityGymDoor                     { 278,  225, 1};  // -> MAP_VERMILION_CITY_GYM
constexpr KantoGoal DiglettsCaveSouthEntranceDoor1           { 318,  217, 1};  // -> MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE
constexpr KantoGoal Route11EastEntrance1fDoor1               { 370,  220, 1};  // -> MAP_ROUTE11_EAST_ENTRANCE_1F
constexpr KantoGoal Route11EastEntrance1fDoor2               { 377,  220, 1};  // -> MAP_ROUTE11_EAST_ENTRANCE_1F
constexpr KantoGoal Route2ViridianForestSouthEntranceDoor3   { 125,   62, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE
constexpr KantoGoal Route2ViridianForestSouthEntranceDoor4   { 124,   62, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE
constexpr KantoGoal Route2ViridianForestNorthEntranceDoor3   { 101,    9, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE
constexpr KantoGoal Route2ViridianForestNorthEntranceDoor4   { 102,    9, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE
constexpr KantoGoal Route2ViridianForestSouthEntranceDoor5   { 126,   62, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE
constexpr KantoGoal Route2ViridianForestNorthEntranceDoor5   { 100,    9, 1};  // -> MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE
constexpr KantoGoal MtMoonB1fDoor2                           {  29,    6, 1};  // -> MAP_MT_MOON_B1F
constexpr KantoGoal MtMoonB1fDoor3                           {  43,   14, 1};  // -> MAP_MT_MOON_B1F
constexpr KantoGoal MtMoonB1fDoor4                           {  55,   16, 1};  // -> MAP_MT_MOON_B1F
constexpr KantoGoal Route4Door1                              {  42,   37, 1};  // -> MAP_ROUTE4
constexpr KantoGoal MtMoon1fDoor2                            { 153,    3, 1};  // -> MAP_MT_MOON_1F
constexpr KantoGoal MtMoon1fDoor3                            { 175,    4, 1};  // -> MAP_MT_MOON_1F
constexpr KantoGoal MtMoon1fDoor4                            { 193,   21, 1};  // -> MAP_MT_MOON_1F
constexpr KantoGoal MtMoonB2fDoor1                           { 172,   18, 1};  // -> MAP_MT_MOON_B2F
constexpr KantoGoal MtMoonB2fDoor2                           { 167,    5, 1};  // -> MAP_MT_MOON_B2F
constexpr KantoGoal MtMoonB2fDoor3                           { 176,   36, 1};  // -> MAP_MT_MOON_B2F
constexpr KantoGoal MtMoonB2fDoor4                           { 189,    4, 1};  // -> MAP_MT_MOON_B2F
constexpr KantoGoal Route4Door2                              { 195,    4, 1};  // -> MAP_ROUTE4
constexpr KantoGoal MtMoonB1fDoor5                           { 224,   21, 1};  // -> MAP_MT_MOON_B1F
constexpr KantoGoal MtMoonB1fDoor6                           { 230,   11, 1};  // -> MAP_MT_MOON_B1F
constexpr KantoGoal MtMoonB1fDoor7                           { 216,   31, 1};  // -> MAP_MT_MOON_B1F
constexpr KantoGoal MtMoonB1fDoor8                           { 204,   10, 1};  // -> MAP_MT_MOON_B1F
constexpr KantoGoal DiglettsCaveB1fDoor1                     {   6,    4, 1};  // -> MAP_DIGLETTS_CAVE_B1F
constexpr KantoGoal Route2Door                               {   4,    6, 1};  // -> MAP_ROUTE2
constexpr KantoGoal DiglettsCaveNorthEntranceDoor2           { 159,  163, 1};  // -> MAP_DIGLETTS_CAVE_NORTH_ENTRANCE
constexpr KantoGoal DiglettsCaveSouthEntranceDoor2           { 238,  231, 1};  // -> MAP_DIGLETTS_CAVE_SOUTH_ENTRANCE
constexpr KantoGoal Route11Door                              {  14,    6, 1};  // -> MAP_ROUTE11
constexpr KantoGoal DiglettsCaveB1fDoor2                     {  16,    4, 1};  // -> MAP_DIGLETTS_CAVE_B1F
constexpr KantoGoal Route10Door1                             { 197,   72, 1};  // -> MAP_ROUTE10
constexpr KantoGoal RockTunnelB1fDoor1                       { 225,   72, 1};  // -> MAP_ROCK_TUNNEL_B1F
constexpr KantoGoal RockTunnelB1fDoor2                       { 184,   72, 1};  // -> MAP_ROCK_TUNNEL_B1F
constexpr KantoGoal RockTunnelB1fDoor3                       { 200,   83, 1};  // -> MAP_ROCK_TUNNEL_B1F
constexpr KantoGoal RockTunnelB1fDoor4                       { 225,   91, 1};  // -> MAP_ROCK_TUNNEL_B1F
constexpr KantoGoal Route10Door2                             { 198,  107, 1};  // -> MAP_ROUTE10
constexpr KantoGoal RockTunnel1fDoor3                        { 350,   98, 1};  // -> MAP_ROCK_TUNNEL_1F
constexpr KantoGoal RockTunnel1fDoor4                        { 345,   73, 1};  // -> MAP_ROCK_TUNNEL_1F
constexpr KantoGoal RockTunnel1fDoor5                        { 339,   82, 1};  // -> MAP_ROCK_TUNNEL_1F
constexpr KantoGoal RockTunnel1fDoor6                        { 314,   73, 1};  // -> MAP_ROCK_TUNNEL_1F
constexpr KantoGoal UndergroundPathNorthEntranceDoor2        {  28,   43, 1};  // -> MAP_UNDERGROUND_PATH_NORTH_ENTRANCE
constexpr KantoGoal UndergroundPathSouthEntranceDoor2        {  27,  100, 1};  // -> MAP_UNDERGROUND_PATH_SOUTH_ENTRANCE
constexpr KantoGoal UndergroundPathEastEntranceDoor2         { 376,   23, 1};  // -> MAP_UNDERGROUND_PATH_EAST_ENTRANCE
constexpr KantoGoal UndergroundPathWestEntranceDoor2         { 303,   24, 1};  // -> MAP_UNDERGROUND_PATH_WEST_ENTRANCE
constexpr KantoGoal CeruleanCityDoor                         { 129,  111, 1};  // -> MAP_CERULEAN_CITY
constexpr KantoGoal CeruleanCave2fDoor1                      { 130,   92, 1};  // -> MAP_CERULEAN_CAVE_2F
constexpr KantoGoal CeruleanCaveB1fDoor                      {  97,   97, 1};  // -> MAP_CERULEAN_CAVE_B1F
constexpr KantoGoal CeruleanCave2fDoor2                      { 106,   92, 1};  // -> MAP_CERULEAN_CAVE_2F
constexpr KantoGoal CeruleanCave2fDoor3                      { 101,  105, 1};  // -> MAP_CERULEAN_CAVE_2F
constexpr KantoGoal CeruleanCave2fDoor4                      { 126,  100, 1};  // -> MAP_CERULEAN_CAVE_2F
constexpr KantoGoal CeruleanCave2fDoor5                      { 120,  101, 1};  // -> MAP_CERULEAN_CAVE_2F
constexpr KantoGoal CeruleanCave2fDoor6                      {  98,   94, 1};  // -> MAP_CERULEAN_CAVE_2F
constexpr KantoGoal CeruleanCave1fDoor2                      { 141,   97, 1};  // -> MAP_CERULEAN_CAVE_1F
constexpr KantoGoal CeruleanCave1fDoor3                      { 117,  117, 1};  // -> MAP_CERULEAN_CAVE_1F
constexpr KantoGoal CeruleanCave1fDoor4                      {  97,  117, 1};  // -> MAP_CERULEAN_CAVE_1F
constexpr KantoGoal CeruleanCave1fDoor5                      {  91,  127, 1};  // -> MAP_CERULEAN_CAVE_1F
constexpr KantoGoal CeruleanCave1fDoor6                      { 110,  122, 1};  // -> MAP_CERULEAN_CAVE_1F
constexpr KantoGoal CeruleanCave1fDoor7                      { 107,  123, 1};  // -> MAP_CERULEAN_CAVE_1F
constexpr KantoGoal CeruleanCave1fDoor8                      {  89,  119, 1};  // -> MAP_CERULEAN_CAVE_1F
constexpr KantoGoal SilphCo1fDoor                            { 345,  180, 1};  // -> MAP_SILPH_CO_1F
constexpr KantoGoal SaffronCityCopycatsHouse1fDoor           { 334,  164, 1};  // -> MAP_SAFFRON_CITY_COPYCATS_HOUSE_1F
constexpr KantoGoal SaffronCityDojoDoor                      { 352,  162, 1};  // -> MAP_SAFFRON_CITY_DOJO
constexpr KantoGoal SaffronCityGymDoor                       { 358,  162, 1};  // -> MAP_SAFFRON_CITY_GYM
constexpr KantoGoal SaffronCityHouseDoor                     { 339,  171, 1};  // -> MAP_SAFFRON_CITY_HOUSE
constexpr KantoGoal SaffronCityMartDoor                      { 352,  171, 1};  // -> MAP_SAFFRON_CITY_MART
constexpr KantoGoal SaffronCityPokemonCenter1fDoor           { 336,  188, 1};  // -> MAP_SAFFRON_CITY_POKEMON_CENTER_1F
constexpr KantoGoal SaffronCityMrPsychicsHouseDoor           { 355,  188, 1};  // -> MAP_SAFFRON_CITY_MR_PSYCHICS_HOUSE
constexpr KantoGoal Route7EastEntranceDoor2                  { 320,  177, 1};  // -> MAP_ROUTE7_EAST_ENTRANCE
constexpr KantoGoal Route5SouthEntranceDoor3                 { 346,  155, 1};  // -> MAP_ROUTE5_SOUTH_ENTRANCE
constexpr KantoGoal Route8WestEntranceDoor2                  { 370,  177, 1};  // -> MAP_ROUTE8_WEST_ENTRANCE
constexpr KantoGoal Route6NorthEntranceDoor3                 { 346,  196, 1};  // -> MAP_ROUTE6_NORTH_ENTRANCE
constexpr KantoGoal Route6NorthEntranceDoor4                 { 347,  196, 1};  // -> MAP_ROUTE6_NORTH_ENTRANCE
constexpr KantoGoal Route5SouthEntranceDoor4                 { 347,  155, 1};  // -> MAP_ROUTE5_SOUTH_ENTRANCE
constexpr KantoGoal SaffronCityPokemonTrainerFanClubDoor     { 359,  171, 1};  // -> MAP_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB

//  ---- Every Fly destination (from heal_locations.json) ----
constexpr KantoGoal FlyPalletTown                            {  66,  268, 1};  // HEAL_LOCATION_PALLET_TOWN
constexpr KantoGoal FlyViridianCity                          {  74,  207, 1};  // HEAL_LOCATION_VIRIDIAN_CITY
constexpr KantoGoal FlyPewterCity                            {  65,   86, 1};  // HEAL_LOCATION_PEWTER_CITY
constexpr KantoGoal FlyCeruleanCity                          { 286,   60, 1};  // HEAL_LOCATION_CERULEAN_CITY
constexpr KantoGoal FlyLavenderTown                          { 390,  136, 1};  // HEAL_LOCATION_LAVENDER_TOWN
constexpr KantoGoal FlyVermilionCity                         { 279,  207, 1};  // HEAL_LOCATION_VERMILION_CITY
constexpr KantoGoal FlyCeladonCity                           { 228,  132, 1};  // HEAL_LOCATION_CELADON_CITY
constexpr KantoGoal FlyFuchsiaCity                           { 217,  332, 1};  // HEAL_LOCATION_FUCHSIA_CITY
constexpr KantoGoal FlyCinnabarIsland                        {  74,  392, 1};  // HEAL_LOCATION_CINNABAR_ISLAND
constexpr KantoGoal FlyIndigoPlateau                         {  11,   17, 1};  // HEAL_LOCATION_INDIGO_PLATEAU
constexpr KantoGoal FlySaffronCity                           { 336,  189, 1};  // HEAL_LOCATION_SAFFRON_CITY
constexpr KantoGoal FlyRoute4                                { 168,   56, 1};  // HEAL_LOCATION_ROUTE4
constexpr KantoGoal FlyRoute10                               { 397,   71, 1};  // HEAL_LOCATION_ROUTE10

}
}
}
}
}
#endif
