/*  Kanto Walkable-Mask Corrections (generated)
 *
 *  GENERATED by Scripts/PokemonFRLG/generate_kanto_full_map.py -- do not hand edit.
 *  The mask is ground truth from the decomp now, so there is nothing to correct.
 *  Kept (empty) so the pathfinder's correction-application code still has a
 *  table, and so a future proven-wrong case has somewhere to go.
 */

#ifndef PokemonAutomation_PokemonFRLG_KantoMaskCorrections_Generated_H
#define PokemonAutomation_PokemonFRLG_KantoMaskCorrections_Generated_H

#include <cstdint>

namespace PokemonAutomation{
namespace NintendoSwitch{
namespace PokemonFRLG{

constexpr int KANTO_CORRECTION_COLS = 408;

constexpr uint32_t KANTO_FORCE_BLOCKED[] = {
    0,
};
constexpr int KANTO_FORCE_BLOCKED_COUNT = 0;

}
}
}
#endif
