/*  Kanto Sub-Region Boundaries (generated)
 *
 *  GENERATED by Scripts/PokemonFRLG/generate_kanto_full_map.py -- do not hand edit.
 *  Exact tile bounds for every outdoor city/route and packed-in interior,
 *  derived from the decomp's own connection offsets. Used only for log labels.
 */

#ifndef PokemonAutomation_PokemonFRLG_KantoRegions_Generated_H
#define PokemonAutomation_PokemonFRLG_KantoRegions_Generated_H

namespace PokemonAutomation{
namespace NintendoSwitch{
namespace PokemonFRLG{

struct KantoRegionBounds{
    const char* name;
    int x0, y0, x1, y1;
};

constexpr KantoRegionBounds KANTO_REGIONS[] = {
    { "DiglettsCave_NorthEntrance",    0,    0,   10,    8 },
    { "DiglettsCave_SouthEntrance",   10,    0,   20,    8 },
    { "MtMoon_1F",   24,    0,   72,   40 },
    { "ViridianForest",   96,    0,  150,   69 },
    { "MtMoon_B1F",  150,    0,  199,   40 },
    { "MtMoon_B2F",  199,    0,  247,   40 },
    { "Route24",  276,    0,  300,   40 },
    { "Route25",  300,    0,  372,   20 },
    { "IndigoPlateau_Exterior",    0,   10,   24,   30 },
    { "UndergroundPath_EastWestTunnel",  300,   20,  380,   27 },
    { "Route23",    0,   30,   24,  190 },
    { "UndergroundPath_NorthSouthTunnel",   24,   40,   32,  103 },
    { "CeruleanCity",  264,   40,  312,   80 },
    { "Route4",  156,   50,  264,   70 },
    { "Route9",  312,   50,  384,   70 },
    { "Route10",  384,   50,  408,  130 },
    { "PewterCity",   48,   60,   96,  100 },
    { "Route3",   96,   70,  180,   90 },
    { "RockTunnel_1F",  180,   70,  228,  110 },
    { "RockTunnel_B1F",  312,   70,  360,  110 },
    { "Route5",  264,   80,  312,  120 },
    { "CeruleanCave_1F",   96,   90,  136,  113 },
    { "CeruleanCave_B1F",  136,   90,  176,  113 },
    { "Route2",   60,  100,   84,  180 },
    { "CeruleanCave_2F",   84,  113,  124,  136 },
    { "CeladonCity",  180,  120,  240,  160 },
    { "SaffronCity_Connection",  264,  120,  312,  160 },
    { "Route16",  132,  130,  180,  150 },
    { "Route7",  240,  130,  264,  150 },
    { "Route8",  312,  130,  384,  150 },
    { "LavenderTown",  384,  130,  408,  150 },
    { "Route17",  132,  150,  156,  310 },
    { "SaffronCity",  312,  150,  378,  205 },
    { "Route12",  384,  150,  408,  270 },
    { "DiglettsCave_B1F",  156,  160,  241,  240 },
    { "Route6",  276,  160,  300,  200 },
    { "ViridianCity",   48,  180,   96,  220 },
    { "Route22",    0,  190,   48,  214 },
    { "VermilionCity",  264,  200,  312,  240 },
    { "Route11",  312,  210,  384,  230 },
    { "Route1",   60,  220,   84,  260 },
    { "PalletTown",   60,  260,   84,  280 },
    { "Route14",  312,  270,  336,  330 },
    { "Route13",  336,  270,  408,  290 },
    { "Route21_North",   60,  280,   84,  330 },
    { "FuchsiaCity",  192,  300,  240,  340 },
    { "Route18",  132,  310,  192,  330 },
    { "Route15",  240,  310,  312,  330 },
    { "Route21_South",   60,  330,   84,  380 },
    { "Route19",  204,  340,  228,  400 },
    { "CinnabarIsland",   60,  380,   84,  400 },
    { "Route20",   84,  380,  204,  400 },
};
constexpr int KANTO_REGIONS_COUNT = 52;

}
}
}
#endif
